spring:
  profiles:
    default: local
  datasource:
    url: jdbc:h2:mem:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.jdbc: debug
